version: '3.8'
services: 
   mysql:
      image: mysql:8.0.28      
      container_name: mysql
      ports:
         - 3306:3306
      environment:
         MYSQL_USER: usuario
         MYSQL_PASSWORD: passwd
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: db
         